annotations:
  teknoir.org/managed-by: devstudio

nodePort:
  enabled: false
  port: 31017

postgres:
  repository: postgres
  pullPolicy: Always
  tag: 11.5
  db_name: frs
  db_port: 5432
  db_password: postgres
  db_user: postgres
  name: cf-db-data

core:
  repository: exadel/compreface-core
  pullPolicy: Always
  tag: latest
  port: 3000
  replicas: 1
  name: cf-core

api:
  repository: exadel/compreface-api
  pullPolicy: Always
  tag: latest
  port: 8080
  replicas: 1
  name: cf-api

admin:
  repository: exadel/compreface-admin
  pullPolicy: Always
  tag: latest
  port: 8080
  replicas: 1
  name: cf-admin

fe:
  repository: exadel/compreface-fe
  pullPolicy: Always
  tag: latest
  port: 80
  replicas: 1
  name: cf-fe
  nodePort:
    enabled: false
    port: 31017
