annotations:
  teknoir.org/managed-by: devstudio

nodePort:
  enabled: false
  port: 31017

postgres:
  repository: postgres
  pullPolicy: Always
  tag: 11.5
  db_name: frs
  db_port: 5432
  db_password: postgres
  db_user: postgres
  name: cf-db-data

core:
  repository: us-docker.pkg.dev/teknoir/gcr.io/compreface-core
  pullPolicy: Always
  tag: latest
  port: 3000
  replicas: 1
  name: cf-core
  containerArgs: >
    FACE_DETECTION_PLUGIN=insightface.FaceDetector@retinaface_r50_v1
    CALCULATION_PLUGIN=insightface.Calculator@arcface_r100_v1
    EXTRA_PLUGINS=insightface.LandmarksDetector,insightface.GenderDetector,insightface.AgeDetector
    BASE_IMAGE=compreface-core-base:base-cuda100-py37
    GPU_IDX=0

api:
  repository: us-docker.pkg.dev/teknoir/gcr.io/compreface-api
  pullPolicy: Always
  tag: latest
  port: 8080
  replicas: 1
  name: cf-api

admin:
  repository: us-docker.pkg.dev/teknoir/gcr.io/compreface-admin
  pullPolicy: Always
  tag: latest
  port: 8080
  replicas: 1
  name: cf-admin

fe:
  repository: us-docker.pkg.dev/teknoir/gcr.io/compreface-fe
  pullPolicy: Always
  tag: latest
  port: 80
  replicas: 1
  name: cf-fe
  nodePort:
    enabled: false
    port: 31580
