apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: core
  name: {{ .Values.core.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- toYaml $.Values.annotations | nindent 4 }}
spec:
  replicas: {{ .Values.core.replicas }}
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      labels:
        app: core
    spec:
      runtimeClassName: nvidia
      containers:
        - image: {{ .Values.core.repository }}:{{ .Values.core.tag }}
          ports:
          - containerPort: {{ .Values.core.port }}
          name: {{ .Values.core.name }}
          command: [ "uwsgi", "--ini", "uwsgi.ini", "--buffer-size=83146" ]
          args:
              - |-
                {{ tpl .Values.core.containerArgs . | nindent 16 }}
          env:
            - name: ML_PORT
              value: "{{ .Values.core.port }}"
            - name: IMG_LENGTH_LIMIT
              value: "640"
            - name: UWSGI_PROCESSES
              value: "2"
            - name: UWSGI_THREADS
              value: "1"
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: compreface-core
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- toYaml $.Values.annotations | nindent 4 }}
spec:
  type: ClusterIP
  selector:
      app: core
  ports:
  - port: {{ .Values.core.port }}
